# Generated by Django 4.1.6 on 2023-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_ratecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecontent',
            name='isApproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratecontent',
            name='schPwd',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
