# Generated by Django 4.1.6 on 2023-03-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_schoolpwd_alter_ratecontent_schpwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecontent',
            name='schPwd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.schoolpwd', to_field='schPwd'),
        ),
        migrations.AlterField(
            model_name='schoolpwd',
            name='schPwd',
            field=models.CharField(default='0000', max_length=4, unique=True),
        ),
    ]
